name: Cypress Tests
on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: windows-latest  # ✅ Use the correct label for Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # ✅ Cypress works best with Node 18 (Node 22 is too new for now)

      - name: Install Dependencies
        run: npm ci  # ✅ Cleaner install for CI

      - name: Verify Cypress Installation
        run: npx cypress verify  # ✅ Ensures binary is downloaded and working

      - name: Run Cypress Tests
        run: npx cypress run  # ✅ More reliable than npm run in CI for Cypress
